### ISSUE TITLE
Some problem on raspberry pi

### ISSUE THREAD

**Issue by alin256** [jvgemert/pbMoMa#7]
I am trying to run the default example with guitar and it brakes after frame 29.
I cannot deduce what is the problem based on the output.
Any ideas or potential fixes? 

Reading: media/guitar.mp4  300 frames  (432 x 192)  FPS:29
Writing: media/guitar.mp4-Mag20Ideal-lo72-hi92.avi
FrameNr: 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 *
Traceback (most recent call last):
  File "phasebasedMoMag.py", line 161, in <module>
    phaseBasedMagnify(vidFname, vidFnameOut, maxFrames, windowSize, factor, fpsForBandPass, lowFreq, highFreq)
  File "phasebasedMoMag.py", line 118, in phaseBasedMagnify
    out = steer.reconSCFpyr(newCoeff)
  File "/usr/local/lib/python2.7/dist-packages/perceptual/filterbank.py", line 184, in reconSCFpyr
    tempdft = self.reconSCFpyrLevs(coeff[1:], log_rad, Xrcos, Yrcos, angle)
  File "/usr/local/lib/python2.7/dist-packages/perceptual/filterbank.py", line 155, in reconSCFpyrLevs
    nlog_rad = log_rad[lostart[0]:loend[0], lostart[1]:loend[1]]
TypeError: slice indices must be integers or None or have an __index__ method

**Comment by wasam-np** [comment]
The issue is due to a change in numpy that broke the code in steerable.
It has been fixed in steerable
https://github.com/andreydung/Steerable-filter/commit/503eff8dfd5e0b616337020e827e294cc3ec2e94 
and I was able to transfer the fix by hand.

In order to fix it right now (without having to wait for the update for steerable):
Open /usr/local/lib/python2.7/dist-packages/perceptual/filterbank.py in your favourite text editor.
Replace lines 152, and 154 with the lines from the link above.
