### ISSUE TITLE
Error when working on default file

### ISSUE THREAD

**Issue by cygerts** [jvgemert/pbMoMa#8]
When running the code on the default video I get output as below. Any suggestions what might resolve the issue?

Reading: media/guitar.mp4  300 frames  (432 x 192)  FPS:29
Writing: media/guitar.mp4-Mag20Ideal-lo72-hi92.avi
FrameNr: 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 *Traceback (most recent call last):
  File "/home/sebek/workspace/INUSER/pbMoMa-master/phasebasedMoMag.py", line 162, in <module>
    phaseBasedMagnify(vidFname, vidFnameOut, maxFrames, windowSize, factor, fpsForBandPass, lowFreq, highFreq)
  File "/home/sebek/workspace/INUSER/pbMoMa-master/phasebasedMoMag.py", line 119, in phaseBasedMagnify
    out = steer.reconSCFpyr(newCoeff)
  File "/usr/local/lib/python2.7/dist-packages/perceptual/filterbank.py", line 184, in reconSCFpyr
    tempdft = self.reconSCFpyrLevs(coeff[1:], log_rad, Xrcos, Yrcos, angle)
  File "/usr/local/lib/python2.7/dist-packages/perceptual/filterbank.py", line 155, in reconSCFpyrLevs
    nlog_rad = log_rad[lostart[0]:loend[0], lostart[1]:loend[1]]
TypeError: slice indices must be integers or None or have an __index__ method

**Comment by tmills** [comment]
This is the same as #7. See that answer for a solution.

**Comment by cygerts** [comment]
great, problem solved. Thx!
